### ISSUE TITLE
Issue numbers zero

### ISSUE THREAD

**Issue by Tillerino** [pweingardt/mylyn-gitlab#14]
I set up a gitlab connector and it seems to be working just fine (haven't modified anything yet) except that all the issues have number 0. Unfortunately this is at work, so I can't provide too much details. I am connecting over HTTP with saved password and we are running gitlab version 6.0.2 10b0b8f.

I took a quick look at the API docs and it seems that the version that we are using does not yet contain the iid field for issues. Would it be possible to use the global id as a fallback?

**Comment by pweingardt** [comment]
I might use the global ID, but it is rather pointless.... you can not reference it in the comments, etc. Why do you want to see the global ID, even if it is useless?

**Comment by samrocketman** [comment]
I believe mylyn gitlab is using the `iid` from the API instead of the global `id`.  The project based `iid` didn't come out until GitLab 6.5.  So I'd say it's probably about time you upgraded your GitLab instance.  The current revision of GitLab is 7.6.2 and 7.7 is slated for release in a few days.

**Comment by pweingardt** [comment]
I am guessing that this issue has been resolved by updating the Gitlab server?

**Comment by Tillerino** [comment]
I wish. It's unfortunately not in my control. All of mylyn was causing
problems all over the place tho, so we stopped using it.

**Comment by samrocketman** [comment]
It makes sense.  mylyn gitlab is designed for recent versions of GitLab.  6.2 was released a couple years ago.  I recommend hiring someone willing to care and feed your GitLab server.  Something like that neglected can be detrimental to productivity.

This issue can be closed I presume.

**Comment by samrocketman** [comment]
Tip to @pweingardt, it would be good to tag and release versions with documentation.  If you had tagged and released versions you could have documented things like using `iid`.  At the very least the OP would know which older version of mylyn gitlab to use for their version of GitLab.  In general, releasing is good to solve issues like that.

**Comment by Tillerino** [comment]
Preaching to the choir, my man :)

Don't keep the issue open on my account.

**Comment by pweingardt** [comment]
@samrocketman I agree... maybe I will switch to gitflow or a slightly less complicated version of gitflow, so that those kind of changes are easy to keep track of.

I will close this for now.

**Comment by samrocketman** [comment]
@Tillerino If you checkout mylyn-gitlab at 02ff95bddfef78807c6de9ad9c333ff0367a02ef it _should_ work for older versions of GitLab such as your installation.
