### ISSUE TITLE
Tickets open on the Context tab instead of the "Gitlab Issue" one

### ISSUE THREAD

**Issue by mcepl** [pweingardt/mylyn-gitlab#17]
It is kind of confusing to see nothing when opening new or already exisitng ticket.
![screenshot from 2014-12-24 17 16 00](https://cloud.githubusercontent.com/assets/198999/5549723/91a2a54c-8b90-11e4-9155-2b59e7637287.png)

**Comment by pweingardt** [comment]
On my eclipse this tag doesn't even show up. Could you update your mylyn-gitlab plugin and try again please?

**Comment by kporowski** [comment]
I am experiencing the same issue with 4.4.1 and latest plugin.

'Context' tab is a standard Mylyn tab - it is described in [Mylyn User Guide - Context](https://wiki.eclipse.org/Mylyn/User_Guide#Context).

**Comment by pweingardt** [comment]
Weird. This tab does not show up for me, the whole context menu is greyed out.

**Comment by kporowski** [comment]
All 4 items of Context menu (Attach, Retrieve, Copy to, Clear) are grayed out in my Eclipse as well. Though when I 'Activate Task'  and open a couple of source files, those files are added to 'Elements' pane of 'Context' tab.

**Comment by pweingardt** [comment]
Without the context specific plugin from Mylyn, the tab does not even show up. After installing the plugin I could figure out how to fix this issue.

Thanks for you bug report

**Comment by samrocketman** [comment]
:+1: awesome
