### ISSUE TITLE
Support for SSH Only Repositories

### ISSUE THREAD

**Issue by cstack89** [pweingardt/mylyn-gitlab#23]
My Gitlab repositories are only available via ssh and as far as I can tell, this is not supported. Would it be possible to add a feature to the plugin to connect to the Gitlab server via ssh?

**Comment by samrocketman** [comment]
The GitLab API is not available over SSH as far as I know.  This connector uses the REST API (which is HTTP(S) only) to resolve information and make changes to GitLab.

Can you clarify what you mean?  If you can only access GitLab over SSH, how are you accessing the web interface for issues?

**Comment by cstack89** [comment]
Sorry this was my mistake. When you click to add a task repository it says something like this as the default http(s)://my-gitlab-instance.org/myname/myproject/project.git. So I was typing in my git credentials. When I followed the readme and did this http(s)://my-gitlab-instance.org/myname/myproject and used my standard gitlab credentials everything worked properly.
