### ISSUE TITLE
Creating queries/repositories with Oomph leads to null pointer

### ISSUE THREAD

**Issue by CWolff92** [pweingardt/mylyn-gitlab#25]
When creating a repository using the Eclipse installer "Oomph" it seems like the property "usePrivateToken" is not automatically set which leads to a null pointer at de.weingardt.mylyn.gitlab.core.ConnectionManager line 55.
This is the line:
```java
if(repository.getProperty("usePrivateToken").equals("true"))
```

**Comment by pweingardt** [comment]
This should be resolved in 1.4.0 thanks to your pull request.
