### ISSUE TITLE
Update site redirect => 404

### ISSUE THREAD

**Issue by zoide** [pweingardt/mylyn-gitlab#30]
The update site does not seem to work.

http://pweingardt.github.io/mylyn-gitlab/ redirects to: http://pweingardt.github.io/mylyn-gitlab/ and the last one gives a 404.

Also, in Eclipse (Neon) nothing happens... :(

**Comment by jpstotz** [comment]
Works perfectly here in Eclipse Oxygen using https://pweingardt.github.io/mylyn-gitlab

**Comment by samrocketman** [comment]
@zoide looking at https://github.com/pweingardt/mylyn-gitlab/tree/gh-pages?files=1 this site is not supposed to be browsable.  It only contains jars for the update site.
