### ISSUE TITLE
Subgroups do not work

### ISSUE THREAD

**Issue by mepeisen** [pweingardt/mylyn-gitlab#37]
I created several groups, subgroups etc.

If I add projects to groups (URL http://myhost/group/project.git) works fine.

But having subgroups reports "Invalid path in host"
The URL for subgroups: http://myhost/group/subgroup/project.git

**Comment by charleech** [comment]
The [ConnectionManager.java](https://github.com/pweingardt/mylyn-gitlab/blob/master/de.weingardt.mylyn.gitlab.core/src/de/weingardt/mylyn/gitlab/core/ConnectionManager.java) uses regular expression as `((?:http|https)://(?:.*))/((?:[^\\/]*?)/(?:[^\\/]*?))$` which gives us the invalid URL to connecting to the GitLab server.

```java

private static Pattern URLPattern = Pattern.compile("((?:http|https)://(?:.*))/((?:[^\\/]*?)/(?:[^\\/]*?))$");

Matcher matcher = URLPattern.matcher(repository.getUrl());
if(!matcher.find()) {
	throw new GitlabException("Invalid Project-URL!");
}

String projectPath = matcher.group(2);

String host = matcher.group(1); // <-- here is the suspected point

String username = repository.getCredentials(AuthenticationType.REPOSITORY).getUserName();
String password= repository.getCredentials(AuthenticationType.REPOSITORY).getPassword();

GitlabSession session = null;
if(repository.getProperty("usePrivateToken") != null && repository.getProperty("usePrivateToken").equals("true")) {
	session = GitlabAPI.connect(host,  password).getCurrentSession();
} else {
	session = GitlabAPI.connect(host, username, password);
}

GitlabAPI api = GitlabAPI.connect(host, session.getPrivateToken());
```

If we enter the `http://a.example.com/group1/group2/project1`, that pattern is compiled as `host = matcher.group(1)` will give us the invalid host as `http://a.example.com/group1`.

Not only this, in my environment, we host the GitLab under the context root as  `http://a.example.com/gitlab`. If we enter  `http://a.example.com/gitlab/group1/group2/project1`, the host will be  `http://a.example.com/gitlab/group1`.

We can test that regular expression at http://www.regexplanet.com/advanced/java/index.html

**Comment by pweingardt** [comment]
should work now

**Comment by sdegrande** [comment]
Confirmed. 
Works well, now (with a https://<server>/<group>/<subgroup>/<project> URL).
Thanks a lot !

**Comment by wandth** [comment]
I just created my first project on gitlab...entered the git URl straight into the Mylyn dialog and I also get the "Invalid path in host" error.

My url looks like this: https://gitlab.com/{USER}/{PROJECT}.git

{PROJECT} has a "-" but with just an alphabetical name it also does not work. Same error!

**Comment by tstsogoo** [comment]
https://gitlab.com/example.example/examaple.tld.git not work.
"Invalid path in host" error.
