### ISSUE TITLE
"Invalid username/password/private token combination" when using OmniAuth

### ISSUE THREAD

**Issue by mvossi** [pweingardt/mylyn-gitlab#40]
We are using GitLab with OmniAuth (SAML with MS Azure) for login. When trying to access a project in GitLab with the Eclipse-GitLab-Connector it returns "Invalid username/password/private token combination", no matter if I try simple username or extended username (email address). When using private token it shows 'Unknown Exception: java.io.IOException: {"message":"401 Unauthorized"}'. So, there's no method left I can use to authenticate against GitLab.

**Comment by stv0g** [comment]
I can confirm this

**Comment by LuisPeregrina** [comment]
The last code change happened a year ago. I'm thinking this project is dead.

**Comment by pweingardt** [comment]
Yes, I am sorry I wasn't able to maintain the project properly :-( . Switched to IntelliJ at my job, then got a new job that has nothing to do with java. 

But the issue should be fixed now.
