### ISSUE TITLE
Not able to connect with private token

### ISSUE THREAD

**Issue by vseibtb** [pweingardt/mylyn-gitlab#41]
I'm not able to connect to a gitlab-repository with my private token.
"Validate Setting" gives ` java.io.IOException: {"message":"401 Unauthorized"}`.

Without the checkbox "Validate on Finish" the setting of the private token is not saved.

Connecting with UserID/password works fine.

I was trying with eclipe Mars and Neon to Gitlab 9.0.5 and previous versions (dockerized).

**Comment by vseibtb** [comment]
I did not investigate enough and was using the wrong URL for API access. Sorry!

But with the correct API-URL I'm getting "Invalid path in host".

Our Gitlab instance is running as a docker container behind an apache webserver with an URL like `https://buildserver-name/gitlab`.

Accessing issues with curl using the same URL I'm trying whit the gitlab-connector works fine.

**Comment by yookoala** [comment]
I have the same issue. I am trying to connect to my private repository at https://gitlab.com.

**Comment by yookoala** [comment]
[Lukas Glowania](https://marketplace.eclipse.org/user/lglowania) also report the same issue on [Eclipse Marketplace](https://marketplace.eclipse.org/comment/4602#comment-4602)

**Comment by pweingardt** [comment]
Should be fixed now

**Comment by vseibtb** [comment]
With the latest version (1.5.0) I am getting "Invalid path in host" every time, even if I use UserID/Password, which worked previously. So with this version I can not connect in any way.

Our Gitlab instance is running as a docker container behind an apache webserver with an URL like `https://buildserver-name/gitlab`.

Can you please give an example for an URL using the Gitlab-API?
