### ISSUE TITLE
Unable to connect to a server with additional application-path

### ISSUE THREAD

**Issue by vseibtb** [pweingardt/mylyn-gitlab#44]
Our Gitlab-instance runs on a docker-container on our buildserver and is accessible only through an apache-webserver.

So the URL has the format `https://buildserver/gitlab/namespace/project.git`, so there is an additional part in the path identifying the application, before the rest of the path that identifies the location inside the application.

In version 1.5.0 for issues #37 and #42 the URL-pattern was changed to allow subprojects, having URLs like `https://gitlab-server/group/subgroup/project.git`.

After this change we are no longer able to connect to our projects, because the URL is now parsed as 

**service-URL**=`https://buildserver` and **location**=`gitlab/namespace/project.git` 

instead of

**service-URL**=`https://buildserver/gitlab` and **location**=`namespace/project.git`.

As can easily be seen, the patterns of this two scenarios (application-namespace and subgroups) are equivalent and can not be distinguished by simple pattern-matching.

In my opinion, the only promising solution will be to split the input-field in the gui to "_Service-URL_" (like `https://myhost`, `https://gitlab-host:12345` or `https://my-buildserver/gitlab-app`) and "_Project-location_" (like `group/subgroup/project.git` or `namespace/project.git`).

**Comment by pweingardt** [comment]
Today I released a new version (1.6.0). You should be able to enter the gitlab base url with that plugin. I hope it works. I have no way to test it thoroughly though.

**Comment by vseibtb** [comment]
This solution works for me, thanks a lot!!

At the moment the update-site http://pweingardt.github.com/mylyn-gitlab does not work, so I built the plugin on my local machine.

By the way: you can remove the "Maven generally ... first project" item from your README.md. I was able to build the project an Windows 7 and Ubuntu-Linux 14.04 (Java8-oracle-144 and maven 3.3.9 respectively 3.0.5) without any problems.

**Comment by pweingardt** [comment]
Hi.
Thanks for the heads up, the update page should work now again.
Yeah, next time I make a commit, I will remove that part.

Thanks for your input :) .
