### ISSUE TITLE
Project Health and Unsupported with API-V4 

### ISSUE THREAD

**Issue by kferrone** [pweingardt/mylyn-gitlab#53]
We just upgraded Gitlab and now I can't sync anymore because Gitlab upgraded to API-V4. This plugin is still using API-V3 and I can't sync my issues anymore :(

I see the last commit was in Aug 2017 a whole year ago and the last issue report was in February. 

Does the project still live? 

Any chances we get an update to support API-V4?

**Comment by wandth** [comment]
Having the same problem. Would love to see an update to this plugin.

**Comment by scriptninja** [comment]
I tried to fork from Ausov's fork of PhilMFischer's fork (which both seem to be addressing this, at least in part) and get a TravisCI build set up to deploy the update site to Github Pages, but this is sufficiently not my area of expertise that once the build failed I don't really have any idea where to go from there.

**Comment by nicosmeenk** [comment]
Same Problem here!

**Comment by nelson777** [comment]
I made it work. Described what I did in my own answer to my StackOverflow question here: https://stackoverflow.com/questions/51048385/invalid-tls-certificate-when-connecting-mylyn-to-gitlab-issues/52337839#52337839

**Comment by kferrone** [comment]
@nelson777 
I was unable to follow those instructions in the SO question all the way. I failed running `mvn clean verify` on the second repo with the following. (There was a lot more if needed)

```
[ERROR] Internal error: java.lang.RuntimeException: Could not instantiate required component: com.google.inject.ProvisionException: Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) Error notifying InjectionListener org.eclipse.sisu.plexus.PlexusBeanBinder@60c8a093 of org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.
[ERROR]  Reason: java.lang.RuntimeException: java.lang.RuntimeException: Exception in org.eclipse.osgi.framework.internal.core.SystemBundleActivator.start() of bundle org.eclipse.osgi.
[ERROR]   while locating org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver
[ERROR]   at ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:0.19.0, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@4f8e5cde] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
[ERROR]   while locating org.eclipse.tycho.core.TargetPlatformResolver annotated with @com.google.inject.name.Named(value="p2")
[ERROR] 
[ERROR] 1 error
[ERROR]       role: org.eclipse.tycho.core.TargetPlatformResolver
[ERROR]   roleHint: p2: The System Bundle could not be resolved: Missing Constraint: Bundle-RequiredExecutionEnvironment: J2SE-1.5
[ERROR] -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Could not instantiate required component
```

Eclipse: Photon (4.8.0)
MacOS: 10.13.6
Java: 9

Is my environment the issue? What's your environment? Any idea what's wrong here?

**Comment by nelson777** [comment]
Probably... I compiled it in Java 8, Ubuntu 16.04 64 bits and used Eclipse Oxygen. The problem is my Java year are way back, and I know only the basic. Why don't you try to reproduce the ambient first and see if it works for you. Maybe a virtual machine or a docker container. If it works, you install java 8 in your machine, try again, etc...

**Comment by nelson777** [comment]
@kferrone if you really post the question in SO as I mentioned, please link it here. Thanks.

**Comment by pweingardt** [comment]
Hello guys, original developer here,

Sorry I haven't been able to keep the project up to date, a lot of other things to do right now, and sadly, I personally do not use the plugin anymore. Anyway I actually didn't know that other people were still using the plugin and I will look into the issues on this weekend. I guess it won't need too much work. Probably updating the gitlab-api library and hopefully that will be it.

Again, sorry for the huge delay. I will try to update the project next weekend.

**Comment by pweingardt** [comment]
Project is up to date and working with Gitlab API v4.
Sorry for the delay.

**Comment by kferrone** [comment]
Whoot whoot!!! Thank you good sir. Love having my tasks as first class citizens of my Eclipse. I have been trying to find time to contribute. Would be a nice refresher on Java for me too since it's been quite a while. Hopefully more people get on board with this plugin so it can stay alive and well. Good luck and keep up the good work!

**Comment by fogs** [comment]
Cheers, man. Thanks for the patch. Especially since you are not using the tool yourself anymore. Keep up the open source spirit.
